name: conventional
description: A light-weight conventional commit parser and tools
version: 0.0.2-pre
homepage: https://github.com/asartalo/conventional

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  equatable: ^2.0.0-nullsafety.1
  pub_semver: ^2.0.0

dev_dependencies:
  lint: ^1.5.1
  path: ^1.7.0
  test: ^1.14.4
