name: conventional
description: A light-weight conventional commit parser and tools
version: 0.0.1
homepage: https://github.com/asartalo/conventional

environment:
  sdk: '>=2.12.0-29.beta <3.0.0'

dependencies:
 pub_semver: ^2.0.0-nullsafety.0
 equatable: ^2.0.0-nullsafety.1

dev_dependencies:
  lint: ^1.5.1
  test: ^1.14.4
