name: conventional
description: A light-weight library for working with commits that follow the Conventional Commits specification.
version: 0.4.0
homepage: https://github.com/asartalo/conventional

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  petitparser: ^6.0.1
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.7.1
  git_hooks: ^1.0.1
  lint: ^2.2.0
  mutex: ^3.1.0
  path: ^1.8.3
  test: ^1.24.9
