name: conventional
description: A light-weight library for working with commits that follow the Conventional Commits specification.
version: 0.1.0
homepage: https://github.com/asartalo/conventional

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  pub_semver: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  coverage: ^1.0.1
  lint: ^1.5.1
  path: ^1.7.0
  test: ^1.14.4
