name: conventional
description: A light-weight library for working with commits that follow the Conventional Commits specification.
version: 0.3.1
homepage: https://github.com/asartalo/conventional

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  petitparser: ^5.0.0
  pub_semver: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  coverage: ^1.5.0
  git_hooks:
    git:
      url: https://github.com/asartalo/git_hooks.git
      ref: null-safety-2
  lint: ^1.5.1
  mutex: ^3.0.0
  path: ^1.7.0
  test: ^1.14.4
