name: Continuous integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  test:
    name: Tests
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:

    - uses: cedx/setup-dart@v2
      with:
        release-channel: stable

    # Checkout
    - uses: actions/checkout@v2

    # Get dependencies.
    - run: pub get

    # Check for any formatting issues in the code.
    - run: dart format --set-exit-if-changed .

    # Statically analyze the Dart code for any errors.
    - run: dart analyze .

    # Run widget tests for our flutter project.
    - run: dart test